import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
// import Navbar from "./Navbar/page";
// import NavBarItem from "./Navbar/topNavbar";
// import Navbar from "@/dashboad/Navbar.tsx/page";
// import NavBarItem from "@/dashboad/Navbar.tsx/navBarItem";
import NextTopLoader from 'nextjs-toploader';
import { ThemeProvider } from "@/components/theme-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// context api
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
     
      <body  suppressHydrationWarning  className={cn("    h-screen  antialiased bg-[#F8F7FA]  dark:bg-zinc-900 text-black dark:text-white  w-full ",
        inter.className)}>
        {/* <Navbar/> */}
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        <NextTopLoader />

        {children}
        {/* <div className=" sticky top-0 z-50  flex justify-between">
        <div className="xl:w-60 "> <Navbar/>  </div>
        <div className="w-screen sticky top-0 z-50"> <NavBarItem/>  </div>
      </div> */}

</ThemeProvider>
      </body>
     
    </html>
  );
}
