import type { Metadata } from "next";
import { Inter, M_PLUS_1 } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
// import Navbar from "./Navbar/page";
// import NavBarItem from "./Navbar/topNavbar";
// import Navbar from "@/dashboad/Navbar.tsx/page";
// import NavBarItem from "@/dashboad/Navbar.tsx/navBarItem";
import NextTopLoader from 'nextjs-toploader';
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { AuthProvider } from "./Provider";
import { Toaster } from "@/components/ui/toaster"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// context api
export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={cn("   h-full   antialiased bg-[#F8F7FA]  dark:bg-zinc-900 text-black dark:text-white  w-full ",
        )}>
        {/* <Navbar/> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <AuthProvider>
          <NextTopLoader />

       
          {children}
        
        </AuthProvider>
        <Toaster />
        </ThemeProvider>
      </body>
     
    </html>
  );
}
